---
dependencies:
- name: doccano-postgres
  version: 0.0.0
  repository: file://deps/doccano-postgres
- name: doccano-rabbitmq
  version: 0.0.0
  repository: file://deps/doccano-rabbitmq
- name: base-named-templates-chart
  version: 0.0.0
