---
dependencies:
  - name: error-pages-chart
    version: 1.0.1-vdev
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: louketo-proxy-chart
    version: 1.0.1-vdev
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: keycloak-chart
    version: 11.0.2-vdev
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: gpu-prom-exporter-chart
    condition: global.gpu_support
    version: 0.1.0-vdev
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: traefik-chart
    version: 2.3-vdev
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: kube-dashboard-chart
    version: 2.0.3-vdev
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: kube-helm-chart
    version: 1.0-vdev
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  # - name: metrics-server
  #   version: v0.3.7
  #   repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public