---
dependencies:
  - name: base
    version: "0.1.1-vdev"
    repository: file://deps/base
  - name: flow
    version: "0.1.1-vdev"
    repository: file://deps/flow
  - name: meta
    version: "0.1.1-vdev"
    repository: file://deps/meta
  - name: monitoring
    version: "0.1.1-vdev"
    repository: file://deps/monitoring
  - name: store
    version: "0.1.1-vdev"
    repository: file://deps/store
  - name: error-pages-chart
    version: "0.1.1"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: louketo-proxy-chart
    version: "0.1"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: keycloak-chart
    version: "11.0.3-vdev"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: gpu-prom-exporter-chart
    condition: global.gpu_support
    version: "0.1.0"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: traefik-chart
    version: "2.3"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: kube-dashboard-chart
    version: "2.0.3"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: kube-helm-chart
    version: "0.1.1-vdev"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
    