apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-test-graylog
  namespace: graylog-test
  labels:
    app: fluentd
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-test-graylog
  labels:
    app: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-test-graylog
roleRef:
  kind: ClusterRole
  name: fluentd-test-graylog
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd-test-graylog
  namespace: graylog-test
