apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-test-graylog
  namespace: graylog-test
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-test-graylog
  template:
    metadata:
      labels:
        name: fluentd-test-graylog
    spec:
      serviceAccount: fluentd-test-graylog
      serviceAccountName: fluentd-test-graylog
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: fluentd-test-graylog
        image: docker.io/library/fluent-plugin-gelf-hs:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config-graylog
          mountPath: /etc/fluent
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config-graylog
        configMap:
          name: fluentd-test-config-graylog
      - name: config-path
        emptyDir: {}
