---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: {{ .Values.global.monitoring_namespace }}
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: fluentd
        image: {{  .Values.global.registry_url }}/fluentd:2.5.2-vdev
        imagePullPolicy: {{ .Values.global.pull_policy_pods }}
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /etc/fluent
        - name: airflowlogs
          mountPath: /var/airflowlogs
        - name: ctplogs
          mountPath: /var/ctplogs
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: airflowlogs
        hostPath:
          path: {{ .Values.global.fast_data_dir}}/airflow/logs
      - name: ctplogs
        hostPath:
          path: {{ .Values.global.fast_data_dir}}/ctp/logs
      - name: fluentd-config
        configMap:
          name: fluentd-config
      - name: config-path
        emptyDir: {}
      imagePullSecrets:
      - name: registry-secret
---
