# dcm4chee-standalone
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dcm4chee-standalone-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: "1Mi"
{{- if .Values.global.enable_nfs }}
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  nfs:
    server: "10.152.183.15"
    path: "/dcm4che/server_data"
{{- else }}
  storageClassName: host-dir
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}/dcm4che/server_data"
{{- end }}
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.services_namespace }}"
    name: dcm4chee-standalone-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcm4chee-standalone-pv-claim
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Mi"
  volumeName: "dcm4chee-standalone-pv-volume"
---
# dcm4chee-dicom
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dcm4chee-dicom-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: "1Mi"
{{- if .Values.global.enable_nfs }}
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  nfs:
    server: "10.152.183.15"
    path: "/dcm4che/dicom_data"
{{- else }}
  storageClassName: host-dir
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.slow_data_dir }}/dcm4che/dicom_data"
{{- end }}
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.services_namespace }}"
    name: dcm4chee-dicom-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcm4chee-dicom-pv-claim
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Mi"
  volumeName: "dcm4chee-dicom-pv-volume"
---