---
apiVersion: batch/v1
kind: Job
metadata:
  name: cert-init
  namespace: kube-system
spec:
  template:
    metadata:
      name: cert-init
    spec:
      containers:
      - name: cert-init
        image: {{  .Values.global.registry_url }}/cert-init:0.0.1
        imagePullPolicy:  {{ .Values.global.pull_policy_jobs }}
        resources:
          requests:
            memory: 200Mi
          limits:
            memory: 200Mi
        env:
        - name: COMMON_NAME
          value: "kaapana"
        - name: EXPIRATION
          value: "365"
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret