{{- $uuid := uuidv4 | trunc 10 }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mitk-flow-{{ $uuid }}
  namespace: {{ .Values.global.base_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: mitk-flow-{{ $uuid }}
  template:
    metadata:
      labels:
        app-name: mitk-flow-{{ $uuid }}
    spec:
      restartPolicy: Always
      containers:
        # ToDo add init-container to wait for db-host
      - name: mitk
        image: {{  .Values.global.registry_url }}{{  .Values.global.registry_project }}/mitk-flow:1.0-vdev
        imagePullPolicy: {{ .Values.global.pull_policy_pods }}
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "1Gi"
        env:
        - name: INGRESS_PATH
          value: mitk-flow-{{ $uuid }}
        - name: USER
          value: mitk
        - name: PASSWORD
          value: mitk
        - name: WORKFLOW_DIR
          value: {{ .Values.workflow_dir }}
        - name: BATCH_NAME
          value: {{ .Values.batch_name }}
        - name: OPERATOR_OUT_DIR
          value: {{ .Values.operator_out_dir }} 
        - name: OPERATOR_IN_DIR
          value: {{ .Values.operator_in_dir }}           
        volumeMounts:
        - name: mitk-data
          mountPath: /data
      volumes:
      - name: mitk-data
        hostPath:
          path: "{{ .Values.mount_path }}"
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: registry-secret
---
