apiVersion: v1
appVersion: "0.1.0-vdev"
description: A Helm chart for Kubernetes
name:  openmined-grid-chart
version: 0.1.0-vdev
keywords:
# - kaapanaapplication
# - kaapanamultiinstallable
# - kaapanaexperimental