---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-test-config
  namespace: kube-logging-test
data:
  elasticsearch.yml: |
    ---
    cluster.name: elastic-test
    network.host: "0"
    network.port: "9200"
    xpack.security.enabled: true
    xpack.license.self_generated.type: basic
    xpack.monitoring.collection.enabled: true

