---
apiVersion: v1
kind: Service
metadata:
  name: elastic-test-service
  namespace: kube-logging-test
  labels:
    app-name: elastic-test
spec:
  selector:
    app-name: elastic-test
  type: ClusterIP
  ports:
  - name: elastic-rest
    port: 9200
    targetPort: 9200
    protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: elasticsearch-ingress
  namespace: kube-logging-test
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd,kube-system-strip-prefix@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /elastic-test
        backend:
          serviceName: elastic-test-service
          servicePort: elastic-rest
---
