---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-test-de
  namespace: kube-logging-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: elastic-test
  template:
    metadata:
      labels:
        app-name: elastic-test
    spec:
      containers:
        - name: elastic-test-container
          image: dktk-jip-registry.dkfz.de/kaapana/elasticsearch-oss:6.8.12
          imagePullPolicy:  IfNotPresent
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1000m -Xmx1000m"
          ports:
            - containerPort: 9200
          resources:
            requests:
              memory: 1500Mi
            limits:
              memory: 2000Mi
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 15
            periodSeconds: 120
      volumes:
      - name: elastic-config-file
        configMap:
          name: elastic-test-config
      imagePullSecrets:
      - name: registry-secret
---
