---
global:
  pull_policy_pods: "IfNotPresent"
  base_namespace: "base"
  flow_namespace: "flow"
  flow_jobs_namespace: "flow-jobs"
  fast_data_dir: ""
  slow_data_dir: ""
  home_dir: /root
  kaapana_collections:
    - name: kaapana-base-collection
      version: 0.1.0-vdev 