# ctp-logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctp-log-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "100Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}/ctp/logs"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.services_namespace }}"
    name: ctp-log-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctp-log-pv-claim
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
  volumeName: "ctp-log-pv-volume"
---
# ctp-data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctp-data-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "10Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}/ctp"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.services_namespace }}"
    name: ctp-data-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctp-data-pv-claim
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Mi"
  volumeName: "ctp-data-pv-volume"
---