---
apiVersion: batch/v1
kind: Job
metadata:
  name: extensions-init
  namespace: kube-system
spec:
  template:
    metadata:
      name: extensions-init
    spec:
    spec:
      initContainers:
        - name: init
          image: {{  .Values.global.registry_url }}/service_checker:1.1
          imagePullPolicy: {{ .Values.global.pull_policy_jobs }}
          env:
            - name: WAIT
              value: "kube-helm,kube-helm-service.kube-system.svc,5000,/kube-helm-api/health-check"
            - name: DELAY
              value: "2"
            - name: TIMEOUT
              value: "10"
      containers:
      - name: extensions-init
        image: {{  .Values.global.registry_url }}/service_checker:1.1
        command: ["/bin/sh", "-c"]
        args: ["echo -e \"import requests;requests.get('http://kube-helm-service.kube-system.svc:5000/kube-helm-api/update-extensions')\" | python3"]
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 0