# Copy me and only adapt values.yaml and Chart.yaml!
{{ if eq .Values.action "prefetch" }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prefetch-{{ .Values.image }}
  namespace: default
spec:
  selector:
    matchLabels:
      app-name: prefetch-{{ .Values.image }}-{{ .Values.version }}
  template:
    metadata:
      labels:
        app-name: prefetch-{{ .Values.image }}-{{ .Values.version }}
    spec:
      initContainers:
        - name: init
          image: {{  .Values.global.registry_url }}{{ .Values.global.registry_project }}/service_checker:1.1
          imagePullPolicy: {{ .Values.global.pull_policy_jobs }}
          env:
            - name: WAIT
              value: "kube-helm,kube-helm-service.kube-system.svc,5000,/kube-helm-api/health-check"
            - name: DELAY
              value: "2"
            - name: TIMEOUT
              value: "10"
      containers:
      - name: prefetch-{{ .Values.image }}
        image: "{{ .Values.global.registry_url }}/tutorial/{{ .Values.image }}:{{ .Values.version }}"
  #      image: "{{ .Values.global.registry_url }}{{ .Values.global.registry_project }}/{{ .Values.image }}:{{ .Values.version }}"
        env:
          - name: ACTION
            value: {{ .Values.action }}
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
      imagePullSecrets:
        - name: registry-secret
{{ else }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.image }}
  namespace: default
spec:
  template:
    spec:
      initContainers:
        - name: init
          image: {{  .Values.global.registry_url }}{{ .Values.global.registry_project }}/service_checker:1.1
          imagePullPolicy: {{ .Values.global.pull_policy_jobs }}
          env:
            - name: WAIT
              value: "kube-helm,kube-helm-service.kube-system.svc,5000,/kube-helm-api/health-check"
            - name: DELAY
              value: "2"
            - name: TIMEOUT
              value: "10"
      containers:
      - name: copy-{{ .Values.image }}
        image: "{{ .Values.global.registry_url }}/tutorial/{{ .Values.image }}:{{ .Values.version }}"
  #      image: "{{ .Values.global.registry_url }}{{ .Values.global.registry_project }}/{{ .Values.image }}:{{ .Values.version }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_jobs }}
        env:
        - name: ACTION
          value: {{ .Values.action }}
        volumeMounts:
        - name: data
          mountPath: "/workflows"
      # securityContext:
      #   runAsUser: 0
      volumes:
      - name: data
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/workflows
          type: DirectoryOrCreate
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 0
{{ end }}