{{- $uuid := uuidv4 | trunc 10 }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prefetch-extensions-{{ $uuid }}
  namespace: default
spec:
  selector:
    matchLabels:
      app-name: prefetch-extensions-{{ $uuid }}
  template:
    metadata:
      labels:
        app-name: prefetch-extensions-{{ $uuid }}
    spec:
      initContainers:
        - name: init
          image: {{  .Values.global.registry_url }}{{ .Values.global.registry_project }}/service_checker:1.1
          imagePullPolicy: {{ .Values.global.pull_policy_jobs }}
          env:
            - name: WAIT
              value: "kube-helm,kube-helm-service.kube-system.svc,5000,/kube-helm-api/health-check"
            - name: DELAY
              value: "2"
            - name: TIMEOUT
              value: "10"
      containers:
      - name: prefetch-extensions-{{ $uuid }}
        image: {{  .Values.global.registry_url }}{{ .Values.global.registry_project }}/service_checker:1.1
        command: ["/bin/sh", "-c"]
        args: ["echo -e \"import requests;requests.get('http://kube-helm-service.kube-system.svc:5000/kube-helm-api/prefetch-extension-docker')\" | python3"]
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
      imagePullSecrets:
        - name: registry-secret
