---
- hosts: localhost
  gather_facts: no
  vars:
    - target: "{{ target_host }}"
      default: "10.128.128.218"

  tasks:
    - add_host:
        name: "{{ target }}"
        groups: os_server

- name: Copy data and algorithm chart to isolated environment
  hosts: os_server
  strategy: free
  remote_user: "{{ remote_username }}"
  vars:
    #TODO: change hardcoded
    ansible_ssh_private_key_file: ~/.ssh/tfda_iso.pem
    singularity_image_name: docker-to-singularity.sif
  # TODO: data could be in any instance and  multiple instance... todo
  tasks:
    #- name: Download a Image Test
      #get_url:
        #url: https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.0.4
        #dest: /home/ubuntu/
        #mode: 0777

    # - name: Copy data
    #   become: yes
    #   copy:
    #     src: "/home/kaapana/minio/{{ bucket_name }}"
    #     dest: "/home/kaapana/minio"
    #     directory_mode: yes
    #     mode: 0775

    - name: Set algorithm container path
      set_fact: 
        container_path: "{{ tarball_path }}/{{ filename }}"
    
    - name: Copy chart
      # become: yes
      copy:
        src: "{{ container_path }}"
        dest: "/home/ubuntu"
        # directory_mode: yes

    - name: Convert Docker container to Singularity
      shell: 
      args:
        cmd: singularity build {{ singularity_image_name }} docker-archive://{{ filename }}
        chdir: /home/ubuntu

    - name: show me the path and filename
      debug: 
        msg: "Singularity image name is {{ singularity_image_name }} and docker filename is {{ filename }}"
