---
- hosts: localhost
  gather_facts: no
  vars:
    - target: "{{ target_host }}"
      default: "10.128.128.218"
  tasks:
    - add_host:
        name: "{{ target }}"
        groups: os_server

- name: Run algorithm on data in isolated environment and send results back to parent data site
  hosts: os_server
  strategy: free
  gather_facts: yes
  remote_user: "{{ remote_username }}"
  vars:
    #TODO: change hardcoded
    ansible_ssh_private_key_file: ~/.ssh/tfda_iso.pem
  environment:
    PATH: '/home/ubuntu/.local/bin:{{ ansible_env.PATH }}'

  tasks:
    - name: Run MedPerf client on the submission
      shell: /home/ubuntu/.local/bin/medperf --storage=/home/ubuntu/medperf/medperf-env test -b {{ benchmark_id }}
      args:
        chdir: /home/ubuntu/medperf

    - name: Compress results file
      archive: 
        path: /home/ubuntu/medperf/medperf-env/results/{{ benchmark_id }}
        dest: "/home/ubuntu/medperf/medperf-env/results/{{ subm_id }}_results.zip"
        format: zip

    - name: Copy results back to the parent host
      become: yes
      ## Currently Ansible doesn't directly support directory/recursive copying from remote to local
      fetch:
        src: "/home/ubuntu/medperf/medperf-env/results/{{ subm_id }}_results.zip"
        dest: "{{ subm_results_path }}/"
        flat: yes
        