---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: adminer
  namespace: {{ .Values.global.base_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: adminer
  template:
    metadata:
      labels:
        app-name: adminer
    spec:
      containers:
      - name: adminer
        image: {{  .Values.global.registry_url }}{{  .Values.global.registry_project }}/adminer:4.7.6
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
      imagePullSecrets:
      - name: registry-secret
