---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres-mainzelliste
  namespace: "{{ .Values.global.extensions_namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: postgres-mainzelliste
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app-name: postgres-mainzelliste
    spec:
      restartPolicy: Always
      containers:
        - name: postgres
          image: "{{ .Values.global.registry_url }}/postgres-9.6-alpine:{{ .Values.global.kaapana_build_version  }}"
          args: ["-c", "max_connections=200"]
          imagePullPolicy: {{ .Values.global.pull_policy_pods | default "IfNotPresent" }}
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 500Mi
          volumeMounts:
            - name: mainzelliste-postgres-data
              mountPath: "/var/lib/postgresql/data"
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: root
            - name: POSTGRES_DB
              value: mainzelliste
      volumes:
        - name: mainzelliste-postgres-data
          persistentVolumeClaim:
            claimName: mz-postgres-pv-claim
      imagePullSecrets:
      - name: registry-secret