
apiVersion: v1
kind: Service
metadata:
  name: hello-postgres-service
  namespace: base
  #namespace: {{ .Values.global.base_namespace }}
  labels:
    app-name: hello-postgres
spec:
  selector:
    app-name: hello-postgres
  ports:
    - port: 5432
      targetPort: 5432