apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      name: tr-admin
    - protocol: TCP
      port: 80
      name: traefik-http
    - protocol: TCP
      port: 443
      name: traefik-https
  selector:
    app: traefik
---