apiVersion: v1
kind: PersistentVolume
metadata:
  name: security-wazuh-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: {{ .Values.global.fast_data_dir | default "/home/kaapana" }}/security/wazuh
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: security-wazuh-persistent-volume-claim
  namespace: {{ .Values.global.security_namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
status: {}
