apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.security_namespace }}
  name: security-wazuh-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5601
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "1514"
      port: 1514
      targetPort: 1514
    - name: "1515"
      port: 1515
      targetPort: 1515
    - name: "514"
      port: 514
      protocol: UDP
      targetPort: 514
    - name: "55000"
      port: 55000
      targetPort: 55000
  selector:
    app-name: security-wazuh
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: security-wazuh-redirect
  namespace: {{ .Values.global.security_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd
    traefik.ingress.kubernetes.io/preserve-host: "true"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /security-wazuh
        pathType: ImplementationSpecific
        backend:
          service:
            name: security-wazuh-service
            port:
              number: 80
---