# Dags
apiVersion: v1
kind: PersistentVolume
metadata:
  name: extensions-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: "1Mi"
  accessModes:
    - ReadWriteMany
  nfs:
    server: "10.152.183.15"
    path: "/extensions"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.admin_namespace }}"
    name: extensions-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extensions-pv-claim
  namespace: "{{ .Values.global.admin_namespace }}"
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Mi"
  volumeName: "extensions-pv-volume"
---