---
dependencies:
# JIP-SYSTEM
  - name: error-pages
    version: 1.0.1-vdev
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: traefik
    version: 2.2-vdev
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: kube-dashboard
    version: 2.0.3-vdev
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
