---
global:
    pull_policy_pods: "IfNotPresent"
    pull_policy_jobs: "IfNotPresent"
    pull_policy_operators: "IfNotPresent"
    core_namespace: "kube-system"
    hostname: 
    credentials:
        registry_username: "na"
        registry_password: "na"

    http_port: 80
    https_port: 443
    fast_data_dir: /home/kaapana
    slow_data_dir: /home/kaapana
    home_dir: /root
    traefik_nodeport: true
    