---
kind: Service
apiVersion: v1
metadata:
  name: gpu-prom-exporter-service
  namespace: kube-system
spec:
  selector:
    app-name: gpu-prom-exporter
  ports:
    - protocol: TCP
      port: 9445
      name: metrics-port
  type: ClusterIP
---
