dependencies:
  - name: stackrox-central-services
    version: 72.1.0
    repository: https://raw.githubusercontent.com/stackrox/helm-charts/main/opensource/
    # repository: file://./deps/stackrox-central-services
    alias: stackrox-central
  - name: stackrox-secured-cluster-services
    version: 72.1.0
    repository: https://raw.githubusercontent.com/stackrox/helm-charts/main/opensource/
    # repository: file://./deps/stackrox-central-services
    alias: stackrox-cluster