---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: "{{  .Values.global.admin_namespace  }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: keycloak
  template:
    metadata:
      labels:
        app-name: keycloak
    spec:
      initContainers:
      - name: init
        image: "{{ .Values.global.registry_url }}/service-checker:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        env:
          - name: WAIT
            value: "postgres,postgres-keycloak-service.{{  .Values.global.admin_namespace  }}.svc,5432"
          - name: DELAY
            value: "2"
          - name: TIMEOUT
            value: "10"
      containers: 
        - name: keycloak-container
          image: "{{ .Values.global.registry_url }}/keycloak:{{ .Values.global.kaapana_build_version  }}"
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          env:
          - name: KEYCLOAK_ADMIN ### KEYCLOAK_USER
            value: {{ .Values.global.credentials_keycloak_admin_username }}
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: {{ .Values.global.credentials_keycloak_admin_password }}
          - name: KC_DB #DB_VENDOR
            value: "postgres"
          - name: KC_DB_URL #DB_ADDR
            value: "jdbc:postgresql://postgres-keycloak-service.{{  .Values.global.admin_namespace  }}.svc:5432/keycloak" #"http://postgres-keycloak-service.{{  .Values.global.admin_namespace  }}.svc:5432"
          - name: KC_DB_URL_PORT ##DB_PORT
            value: "5432"
          - name: KC_DB_USERNAME #DB_USER
            value: "keycloak"
          - name: KC_DB_PASSWORD #DB_PASSWORD
            value: "keycloak"
<<<<<<< HEAD
          - name: KC_LOG_LEVEL
            value: "INFO"
=======
#          - name: DB_DATABASE
#            value: "keycloak"
          # - name: KEYCLOAK_HTTP_PORT
          #   value: "8080"
          # - name: KEYCLOAK_HTTPS_PORT
          #   value: "8443"
          # - name: ROOT_LOGLEVEL
          #   value: "WARN"
          - name: KC_LOG_LEVEL
            value: "INFO"
          # - name: PROXY_ADDRESS_FORWARDING
          #   value: "true"
>>>>>>> Keycloak update to 19.0.3 finished.
          - name: KC_HOSTNAME_ADMIN_URL
            value: "https://{{ .Values.global.hostname }}/auth" ##"https://keycloak-internal-service.{{  .Values.global.admin_namespace  }}.svc:8443/" ## "localhost"
          - name: KC_HOSTNAME_URL
            value: "https://{{ .Values.global.hostname }}/auth"  ###"https://keycloak-internal-service.{{  .Values.global.admin_namespace  }}.svc:8443/" ## "localhost"
          - name: KC_PROXY
            value: edge
          - name: KC_HTTP_RELATIVE_PATH
            value: "/auth/"
<<<<<<< HEAD
          - name: KC_HTTPS_CERTIFICATE_KEY_FILE
            value: "/etc/x509/https/tls.key"
          - name: KC_HTTPS_CERTIFICATE_FILE
            value: "/etc/x509/https/tls.crt"
=======
          #- name: KC_HOSTNAME_STRICT_HTTPS
          #  value: "true"
>>>>>>> Keycloak update to 19.0.3 finished.
          ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
          - name: admin
            containerPort: 9990
          resources:
            requests:
              memory: 600Mi
            limits:
              memory: 700Mi
          volumeMounts:
            - name: ssl-config-files
              mountPath: /etc/x509/https
              readOnly: true
            # - name: keycloak-realm
            #   mountPath: /opt/keycloak/data/import
          command: 
          - "/opt/keycloak/bin/kc.sh"
          - "--verbose"
          - "start"
<<<<<<< HEAD
=======
          #- --hostname-path=/auth
          # - --import-realm
          #- --optimized
          #- --https-certificate-key-file=/etc/x509/https/tls.key
          #- --https-certificate-file=/etc/x509/https/tls.crt
          #- --proxy=passthrough
>>>>>>> Keycloak update to 19.0.3 finished.
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 20
      volumes:
      # - name: keycloak-realm
      #   configMap:
      #     name: keycloak-config
      - name: ssl-config-files
        secret:
          secretName: certificate
      imagePullSecrets:
      - name: registry-secret
---
