---
apiVersion: v1
data:
  keybindings.json: |-
    // Place your key bindings in this file to override the defaults
    [
        {
            "key": "ctrl+alt+down",
            "command": "editor.action.copyLinesDownAction",
            "when": "editorTextFocus && !editorReadonly"
        },
        {
            "key": "ctrl+shift+alt+down",
            "command": "-editor.action.copyLinesDownAction",
            "when": "editorTextFocus && !editorReadonly"
        },
        {
            "key": "ctrl+alt+up",
            "command": "editor.action.copyLinesUpAction",
            "when": "editorTextFocus && !editorReadonly"
        },
        {
            "key": "ctrl+shift+alt+up",
            "command": "-editor.action.copyLinesUpAction",
            "when": "editorTextFocus && !editorReadonly"
        },
        {
            "key": "ctrl+q",
            "command": "editor.action.addSelectionToNextFindMatch",
            "when": "editorFocus"
        },
        {
            "key": "ctrl+d",
            "command": "-editor.action.addSelectionToNextFindMatch",
            "when": "editorFocus"
        },
        {
            "key": "ctrl+d",
            "command": "editor.action.deleteLines",
            "when": "textInputFocus && !editorReadonly"
        },
        {
            "key": "ctrl+shift+k",
            "command": "-editor.action.deleteLines",
            "when": "textInputFocus && !editorReadonly"
        }
    ]
kind: ConfigMap
metadata:
  name: code-server-config
  namespace: {{ .Values.global.base_namespace }}