# Dags
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dags-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "10Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}/workflows/dags"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.services_namespace }}"
    name: dags-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dags-pv-claim
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Mi"
  volumeName: "dags-pv-volume"
---
# logs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: af-logs-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "10Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}/airflow/logs"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.services_namespace }}"
    name: af-logs-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: af-logs-pv-claim
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Mi"
  volumeName: "af-logs-pv-volume"
---
# plugins
apiVersion: v1
kind: PersistentVolume
metadata:
  name: af-plugins-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "10Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}/workflows/plugins"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.services_namespace }}"
    name: af-plugins-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: af-plugins-pv-claim
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Mi"
  volumeName: "af-plugins-pv-volume"
---
# models
apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "100Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}/workflows/models"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.services_namespace }}"
    name: models-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pv-claim
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Gi"
  volumeName: "models-pv-volume"
---
# data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: af-data-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "10Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}/workflows/data"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.services_namespace }}"
    name: af-data-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: af-data-pv-claim
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Mi"
  volumeName: "af-data-pv-volume"
---