---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-test-config
  namespace: kube-logging-test
data:
  fluent.conf: |
    <match fluent.**>
      @type null
    </match>
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers1.log.pos
      tag kubernetes.*
      read_from_head true
      emit_unmatched_lines true
      <parse>
        @type none
      </parse>
    </source>
    <filter kubernetes.**>
      @type kubernetes_metadata
      verify_ssl false
    </filter>
    <match kubernetes.**>
      @type elasticsearch_dynamic
      include_tag_key true
      time-format %Y-%m-%dT%H:%M:%S.%L
      logstash_format true
      logstash_prefix kubernetes-${record['kubernetes']['namespace_name']}
      host elastic-test-service.kube-logging-test
      user: admin
      password: admin
      port 9200
      reload_connections true
      reconnect_on_error true
      reload_on_failure true
      index_name kubernetes
      default_elasticsearch_version 6.8.12
      <buffer>
        @type file
        path /fluentd/log/elastic-buffer-kubernetes
        flush_thread_count 8
        flush_interval 1s
        queue_limit_length 4
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>
    <source>
      @type tail
      path /var/airflowlogs/**/*.log
      pos_file /var/log/fluentd-containers2.log.pos
      tag airflow.*
      read_from_head true
      emit_unmatched_lines true
      <parse>
        @type none
      </parse>
    </source>
    <match airflow.**>
      @type elasticsearch_dynamic
      include_tag_key true
      time-format %Y-%m-%d %H:%M:%S.%L
      logstash_format true
      logstash_prefix airflow
      host elastic-test-service.kube-logging-test
      port 9200
      reload_connections true
      reconnect_on_error true
      reload_on_failure true
      index_name kubernetes
      default_elasticsearch_version 6.8.12
      <buffer>
        @type file
        path /fluentd/log/elastic-buffer-airflow
        flush_thread_count 8
        flush_interval 1s
        queue_limit_length 4
        retry_max_interval 30
        retry_forever true
      </buffer>
    </match>      
