apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-test
  namespace: kube-logging-test
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-test
  template:
    metadata:
      labels:
        name: fluentd-test
    spec:
      serviceAccount: fluentd-test
      serviceAccountName: fluentd-test
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: fluentd-test
        image: docker.io/library/fluent-plugin-slack:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /etc/fluent
        - name: airflowlogs
          mountPath: /var/airflowlogs
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: airflowlogs
        hostPath:
          path: /home/kaapana/airflow/logs
      - name: fluentd-config
        configMap:
          name: fluentd-test-config
      - name: config-path
        emptyDir: {}
