apiVersion: v1
kind: Service
metadata:
  namespace: stackrox #{{ .Values.global.security_namespace }}
  name: {{ .Values.service_name }}
spec:
  type: NodePort
  ports:
    - name: "stackrox-dashboard"
      port: 80
      targetPort: 8080
      nodePort: 19080
    - name: "stackrox-dashboard-443"
      port: 443
      targetPort: 8443
      nodePort: 19443
  selector:
    app: central
---
# apiVersion: networking.k8s.io/v1 
# kind: Ingress
# metadata:
#   name: security-stackrox-redirect
#   namespace: stackrox #{{ .Values.global.security_namespace }}
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
#     traefik.ingress.kubernetes.io/router.middlewares: stackrox-strip-prefix-stackrox@kubernetescrd, stackrox-rewrite-stackrox@kubernetescrd
# spec:
#   rules:
#   - host: 
#     http:
#       paths:
#       - path: /security-stackrox
#         pathType: Prefix
#         backend:
#           service:
#             name: {{ .Value.service_name }}
#             port:
#               number: 80
# ---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: security-stackrox-redirect
  namespace: stackrox
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: PathPrefix(`/security-stackrox`) #|| HeadersRegexp(`Referer`, `.*security-stackrox.*`) #|| Headers(`X-Custom-Stackrox-Header`, `stackrox`) || Headers(`X-Custom-Stackrox-Response-Header`, `stackrox`)
    middlewares:
      # - name: add-prefix-stackrox
      # - name: strip-prefix-stackrox
      - name: custom-headers-stackrox

    services:
      - name: {{ .Values.service_name }}
        port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: security-stackrox-redirect-2
  namespace: stackrox
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match:  Headers(`X-Custom-Stackrox-Header`, `stackrox`) || HeadersRegexp(`Referer`, `.*security-stackrox.*`)
    middlewares:
      #- name: add-prefix-stackrox
      - name: strip-prefix-stackrox
      - name: custom-headers-stackrox
      - name: test-redirectregex2

    services:
      - name: {{ .Values.service_name }}
        port: 80
---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: strip-prefix-stackrox
#   namespace: stackrox
# spec:
#   stripPrefix:
#     prefixes:
#       - /security-stackrox
#     forceSlash: true
# ---

# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: add-prefix-stackrox
#   namespace: stackrox
# spec:
#   addPrefix:
#     prefix: /security-stackrox
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: custom-headers-stackrox
  namespace: stackrox
spec:
  headers:
    customRequestHeaders:
      X-Custom-Stackrox-Header: "stackrox"
    customResponseHeaders:
      X-Custom-Stackrox-Header: "stackrox"

---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: replace-stackrox
#   namespace: stackrox
# spec:
#   replacePathRegex:
#     regex: ^/security-stackrox/(.*)
#     replacement: /$1
# ---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-redirectregex
  namespace: stackrox
spec:
  redirectRegex:
    regex: ^https://vm-128-206.cloud.dkfz-heidelberg.de/(.*)$
    replacement: https://stackrox.vm-128-206.cloud.dkfz-heidelberg.de/$1

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-redirectregex2
  namespace: stackrox
spec:
  redirectRegex:
    regex: ^https://vm-128-206.cloud.dkfz-heidelberg.de/(?!security-stackrox)(.*)$
    replacement: https://vm-128-206.cloud.dkfz-heidelberg.de/security-stackrox/$1

# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: rewrite-stackrox
#   namespace: stackrox
# spec:
#   plugin:
#     rewrite:
#       rewrites:
#       - regex: /api
#         replacement: /traefik/api
#       - regex: (`.*?)/(?:traefik/(api))
#         replacement: $1/$2