---
dependencies:
  - name: adminer-chart
    version: 4.7.8-vdev
    repository: file://../../../../../../services/applications/adminer/adminer-chart
  - name: code-server-chart
    version: 3.9.1
    repository: file://../../../../../../services/applications/code-server/code-server-chart
  - name: debug-container-chart
    version: 1.0.1-vdev
    repository: file://../../../../../../services/applications/debug-container/debug-container-chart
  - name: jupyterlab-chart
    version: 2.2.8
    repository: file://../../../../../../services/applications/jupyterlab/jupyterlab-chart
  - name: mitk-flow-chart
    version: 2021.02-vdev
    repository: file://../../../../../../services/applications/mitk-flow/mitk-flow-chart
  - name: mitk-flow-workflow
    version: 2021-01-19-vdev
    repository: file://../../../../../../workflows/dag-installer/mitk-flow/mitk-flow-workflow
  - name: mitk-workbench-chart
    version: 2021.02-vdev
    repository: file://../../../../../../services/applications/mitk-workbench/mitk-workbench-chart
  - name: nnunet-workflow
    version: 1.6.5-vdev
    repository: file://../../../../../../workflows/dag-installer/nnunet/nnunet-workflow
  - name: openmined-pysyft-nb-chart
    version: 0.1.0-vdev
    repository: file://../../../../../../services/applications/openmined/openmined-pysyft-nb/openmined-pysyft-nb-chart
  - name: radiomics-workflow
    version: 0.1.1-vdev
    repository: file://../../../../../../workflows/dag-installer/radiomics/radiomics-workflow
  - name: shapemodel-vdev-workflow
    version: 0.1.1-vdev
    repository: file://../../../../../../workflows/dag-installer/shapemodel/shapemodel-vdev-workflow
  - name: tensorboard-chart
    version: 2.4.1
    repository: file://../../../../../../services/applications/tensorboard/tensorboard-chart 
    