apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: "{{  .Values.global.admin_namespace  }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: "{{ .Values.global.registry_url }}/volume-nfs:{{ .Values.global.kaapana_build_version  }}"
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mypvc
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: nfs-pv-claim
          # gcePersistentDisk:
          #   pdName: gce-nfs-disk
          #   fsType: ext4
---