# Dags
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mfs-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "200Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.admin_namespace }}"
    name: mfs-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mfs-pv-claim
  namespace: "{{ .Values.global.admin_namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "200Gi"
  volumeName: "mfs-pv-volume"
---
