---
dependencies:
  - name: dcm4chee-chart
    version: "5.23.1-vdev"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: ohif-chart
    version: "4.7.2-vdev"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: minio-chart
    version: "2021.03.12"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: minio-init-chart
    version: "0.1.2"
    condition: Release.IsInstall
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  # TESTS
  - name: dicom-init-chart
    version: "0.1.0"
    condition: Release.IsInstall
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public