---
dependencies:
  - name: prometheus-chart
    version: "v2.25.0"
    repository: file://../../../../services/monitoring/prometheus/prometheus-chart
  - name: alertmanager-chart
    version: "v0.21.0"
    repository: file://../../../../services/monitoring/alert-manager/alertmanager-chart
  - name: grafana-chart
    version: "7.4.3"
    repository: file://../../../../services/monitoring/grafana/grafana-chart
  - name: kube-state-metrics-chart
    version: "v1.9.7"
    repository: file://../../../../services/monitoring/kube_state_metrics/kube-state-metrics-chart
