---
apiVersion: v1
data:
  auth_role_mapping.json: |
    {
    "/meta":"user",
    "/dcm4chee-arc":"user",
    "/flow":"user",
    "/ohif":"user",
    "/workflowdata":"user",
    "/web-ide":"user",
    "/minio-console":"user",
    "/jupyterlab":"user",
    "/qpsma":"user",
    "/doccano":"user",
    "/kubernetes":"admin",
    "/traefik":"admin",
    "/grafana":"user",
    "/prometheus": "user"
    }
kind: ConfigMap
metadata:
  name: auth-check-config
  namespace: "{{ .Values.global.admin_namespace }}"
