# Dags
apiVersion: v1
kind: PersistentVolume
metadata:
  name: af-postgres-pv-volume
  labels:
    type: local
spec:
  storageClassName: nfs
  capacity:
    storage: "1Mi"
  accessModes:
    - ReadWriteMany
  nfs:
    server: "10.152.183.15"
    path: "/postgres-airflow"

  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.services_namespace }}"
    name: af-postgres-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: af-postgres-pv-claim
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Mi"
  volumeName: "af-postgres-pv-volume"
---
