---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-test-config
  namespace: kube-logging-test
data:
  kibana.yml: |
    ---
    server.name: kibana-test
    server.host: "0"
    server.basePath: "/kibana-test"
    server.rewriteBasePath: true
    elasticsearch.hosts: "http://elastic-test-service.kube-logging-test.svc:9200"
    elasticsearch.username: admin
    elasticsearch.password: admin
