# Dags
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tb-pv-volume
  labels:
    type: local
spec:
  storageClassName: nfs
  capacity:
    storage: "200Mi"
  accessModes:
    - ReadWriteMany
  nfs:
    server: "10.152.183.15"
    path: "/tensorboard"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.services_namespace }}"
    name: tb-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tb-pv-claim
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "50Mi"
  volumeName: "tb-pv-volume"
---
