---
apiVersion: batch/v1
kind: Job
metadata:
  name: get-nnunet-models
  namespace: default
spec:
  template:
    metadata:
      name: get-nnunet-models
    spec:
      hostNetwork: true
      containers:
      - name: nnunet-models
        image: {{  .Values.global.registry_url }}{{  .Values.global.registry_project }}/nnunet-get-models:0.1.0
        imagePullPolicy:  {{ .Values.global.pull_policy_jobs }}
        env:
        - name: TASK
          value: "all"
        volumeMounts:
        - name: models-dir
          mountPath: /models
        - name: cache-volume
          mountPath: /tmp
        resources:
          requests:
            memory: 500Mi
          limits:
            memory: 1000Mi
      volumes:
      - name: models-dir
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/workflows/models
          type: DirectoryOrCreate
      - name: cache-volume
        emptyDir: {}
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 0    