project_name: kaapana-platform-chart
default_version: 0.1.2
offline_mode: 'false'
dev_mode: 'true'
container_registry_url: "registry.hzdr.de/santhosh.parampottupadam/microkubsupgrade"
container_registry_username: "microkubeupdation"
container_registry_password: "79CUgvgzgvZwasq62s65"
fast_data_dir: "/home/kaapana"
slow_data_dir: "/home/kaapana"
http_port: 80
https_port: 443
dicom_port: 11112
auth_node_port: 8000
