apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.global.chart_container_image }}
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: copy-{{ .Values.global.chart_container_image }}
        image: "{{- if .Values.global.custom_registry_url }}{{ .Values.global.custom_registry_url }}{{- else}}{{ .Values.global.registry_url }}{{- end }}{{- if .Values.global.custom_registry_project }}{{ .Values.global.custom_registry_project }}{{- else}}{{ .Values.global.registry_project }}{{- end }}/{{ .Values.global.chart_container_image }}:{{ .Values.global.chart_container_version }}"
        {{- if .Values.global.offline_mode }}
        imagePullPolicy: Never
        {{- else }}
        imagePullPolicy: Always
        {{- end }}
        env:
        - name: ACTION
          value: copy
        - name: CHARTS_DIR
          value: {{ .Values.global.charts_dir }}
        volumeMounts:
        - name: data
          mountPath: /charts
      # securityContext:
      #   runAsUser: 0
      volumes:
      - name: data
        hostPath:
          path: "{{ .Values.global.fast_data_dir }}/charts"
          type: DirectoryOrCreate
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 0