apiVersion: v1
appVersion: "0.1-vdev"
description: A Helm chart for Kubernetes
name: slicer-jl-chart
version: 0.1-vdev
keywords:
- kaapanaextension
- kaapanaint
- kaapanamultiinstallable
- kaapanaexperimental