---
apiVersion: batch/v1
kind: Job
metadata:
  name: nnunet-inference-installer
  namespace: {{ .Values.global.flow_namespace }}
spec:
  template:
    spec:
      containers:
      - name: liver-mri-segmentation
        image: {{  .Values.global.registry_url }}{{  .Values.global.registry_project }}/processing-external/dag-nnunet-inference:0.1-vdev
        imagePullPolicy:  {{ .Values.global.pull_policy_operators }}
        volumeMounts:
        - name: data
          mountPath: "/mount_data"
      volumes:
      - name: data
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/workflows
          type: DirectoryOrCreate
      restartPolicy: Never
      imagePullSecrets:
      - name: camic-registry
  backoffLimit: 0