# Copy me and only adapt values.yaml and Chart.yaml!
apiVersion: batch/v1
kind: Job
metadata:
  name: kaapana-plugin
  namespace: {{ .Values.global.flow_namespace }}
spec:
  template:
    spec:
      initContainers:
        - name: init
          image: {{  .Values.global.registry_url }}{{ .Values.global.registry_project }}/service_checker:1.1
          imagePullPolicy: {{ .Values.global.pull_policy_jobs }}
          env:
            - name: WAIT
              value: "kube-helm,kube-helm-service.kube-system.svc,5000,/kube-helm-api"
            - name: DELAY
              value: "2"
            - name: TIMEOUT
              value: "10"
      containers:
      - name: copy-kaapana-plugin
        image: "dktk-jip-registry.dkfz.de/kaapana-public/kaapana-plugin:0.8-vdev"
        imagePullPolicy:  {{ .Values.global.pull_policy_jobs }}
        env:
        - name: ACTION
          value: {{ .Values.action }}
        volumeMounts:
        - name: data
          mountPath: "/workflows"
      # securityContext:
      #   runAsUser: 0
      volumes:
      - name: data
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/workflows
          type: DirectoryOrCreate
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 0