kind: Deployment
apiVersion: apps/v1
metadata:
  name: jupyterlab{{- if .Values.multi_instance_suffix }}-{{ .Values.multi_instance_suffix }}{{- end }}
  namespace: {{ .Values.global.base_namespace }}
  labels:
    k8s-app: jupyterlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: jupyterlab{{- if .Values.multi_instance_suffix }}-{{ .Values.multi_instance_suffix }}{{- end }}
  template:
    metadata:
      labels:
        app-name: jupyterlab{{- if .Values.multi_instance_suffix }}-{{ .Values.multi_instance_suffix }}{{- end }}
    spec:
      containers:
      - name: jupyterlab
        image: {{  .Values.global.registry_url }}{{  .Values.global.registry_project }}/jupyterlab:1.0-vdev
        imagePullPolicy: {{ .Values.global.pull_policy_pods }}
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "1Gi"
        ports:
        - name: jupyterlab-http
          containerPort: 8888
        env:
        - name: INGRESS_PATH
          value: {{ .Values.ingress_path }}
        volumeMounts:
          - name: miniodata
            mountPath: /appdata
      volumes:
      - name: miniodata
        hostPath:
          {{- if .Values.mount_path }}
          path: {{ .Values.mount_path }}
          {{- else }}
          path: {{ .Values.global.slow_data_dir }}/minio
          {{- end }}
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: camic-registry
