---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: louketo
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: louketo
  template:
    metadata:
      labels:
        app-name: louketo
    spec:
      initContainers:
      - name: init
        image: {{  .Values.global.registry_url }}{{  .Values.global.registry_project }}/service_checker:1.1
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        env:
          - name: WAIT
            value: "keycloak,keycloak-service.kube-system.svc,443"
          - name: DELAY
            value: "3"
          - name: TIMEOUT
            value: "10"
      containers:
        - name: louketo-container
          image: {{  .Values.global.registry_url }}{{  .Values.global.registry_project }}/louketo-proxy:2.3.0-vdev
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          args: ["--config","/app/louketo.cfg"]
          ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
          resources:
            requests:
              memory: 20Mi
            limits:
              memory: 50Mi
          volumeMounts:
            - name: config-file
              mountPath: /app
            - name: ssl-config
              mountPath: /ssl
      volumes:
      - name: ssl-config
        secret:
          secretName: certificate
      - name: config-file
        configMap:
          name: louketo-config
      imagePullSecrets:
      - name: camic-registry
---
