---
kind: Service
apiVersion: v1
metadata:
  name: louketo-service
  namespace: kube-system
spec:
  selector:
    app-name: louketo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      nodePort: {{ .Values.global.http_port }}
      name: http-port
    - protocol: TCP
      port: 8443
      nodePort: {{ .Values.global.https_port }}
      targetPort: https
      name: https-port
  type: NodePort

