---
apiVersion: v1
kind: Service
metadata:
  name: ctp-service
  namespace: flow
  labels:
    app-name: ctp
spec:
  selector:
    app-name: ctp
  ports:
  - name: ctp-port
    port: 80
    targetPort: 1050
    protocol: TCP
  - name: ctp-dcm-port
    port: 11112
    targetPort: 11112
  - name: ctp-http-port
    port: 7777
    targetPort: 7777
---