---
kind: Service
apiVersion: v1
metadata:
  name: mitk-vol{{- if .Values.multi_instance_suffix }}-{{ .Values.multi_instance_suffix }}{{- end }}
  namespace: {{ .Values.global.base_namespace }}
  labels:
    app: mitk-vol
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: pt-mitk-http
  type: ClusterIP
  selector:
    app-name: mitk-vol{{- if .Values.multi_instance_suffix }}-{{ .Values.multi_instance_suffix }}{{- end }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mitk-vol{{- if .Values.multi_instance_suffix }}-{{ .Values.multi_instance_suffix }}{{- end }}
  namespace: {{ .Values.global.base_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /{{ .Values.ingress_path }}
        backend:
          serviceName: mitk-vol{{- if .Values.multi_instance_suffix }}-{{ .Values.multi_instance_suffix }}{{- end }}
          servicePort: pt-mitk-http
---
