---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mitk-vol{{- if .Values.multi_instance_suffix }}-{{ .Values.multi_instance_suffix }}{{- end }}
  namespace: {{ .Values.global.base_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: mitk-vol{{- if .Values.multi_instance_suffix }}-{{ .Values.multi_instance_suffix }}{{- end }}
  template:
    metadata:
      labels:
        app-name: mitk-vol{{- if .Values.multi_instance_suffix }}-{{ .Values.multi_instance_suffix }}{{- end }}
    spec:
      restartPolicy: Always
      containers:
        # ToDo add init-container to wait for db-host
      - name: mitk
        image: {{  .Values.global.registry_url }}{{  .Values.global.registry_project }}/mitk-volume:1.0-vdev
        imagePullPolicy: {{ .Values.global.pull_policy_pods }}
        env:
        - name: INGRESS_PATH
          value: {{ .Values.ingress_path }}
        volumeMounts:
        - name: mitk-data
          mountPath: /data
      volumes:
      - name: mitk-data
        hostPath:
          {{- if .Values.mount_path }}
          path: {{ .Values.mount_path }}
          {{- else }}
          path: {{ .Values.global.slow_data_dir }}/minio
          {{- end }}
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: camic-registry
