---
dependencies:
  - name: kaapana-plugin-chart
    version: "0.1.1-vdev"
    # condition: Release.IsInstall
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: airflow-postgres
    version: "9.6.1-vdev"
    repository: file://deps/airflow-postgres

