---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extensions-pv-claim
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Mi"
  volumeName: "extensions-pv-volume"
---
