# dev-files
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-volume
  labels:
    type: local
spec:
  storageClassName: nfs
  capacity:
    storage: "50Mi"
  accessModes:
    - ReadWriteMany
  nfs:
    server: "10.152.183.15"
    path: "/prometheus"

  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.services_namespace }}"
    name: prometheus-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv-claim
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "50Mi"
  volumeName: "prometheus-pv-volume"
---
