---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio
  namespace: {{ .Values.global.base_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: rstudio
  template:
    metadata:
      labels:
        app-name: rstudio
    spec:
      # initContainers:
      # - name: volume-permissions
      #   image: {{ .Values.global.registry_url }}/busybox:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__1.31
      #   imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
      #   command: ["sh", "-c", "chmod 777 /home"]
      #   volumeMounts:
      #   - name: rstudio-data-vol
      #     mountPath: /home
      #   securityContext:
      #     runAsUser: 0
      # securityContext:
      #   runAsUser: 1000
      containers:
      - name: rstudio-container
        image: {{  .Values.global.registry_url }}/rstudio:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__2022.07.1-554
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        env:
        - name: USER
          value: admin
        - name: PASSWORD
          value: admin
        resources:
          requests:
            memory: 500Mi
          limits:
            memory: 2000Mi
        ports:
        - name: http-port
          containerPort: 8787
        volumeMounts:
          - name: rstudio-data-vol
            mountPath: /home
      volumes:
      - name: rstudio-data-vol
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/rstudio
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: registry-secret
---
