apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rstudio-strip-prefix
  namespace: {{ .Values.global.base_namespace }}
spec:
  stripPrefix:
    prefixes:
    - /rstudio
    - /rst-api
    forceSlash: true
---