apiVersion: v1
kind: Service
metadata:
  name: datamodel-service
  namespace: {{ .Values.global.base_namespace }}
spec:
  selector:
    app-name: datamodel
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: datamodel-http
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: datamodel-strip-prefix
  namespace: {{ .Values.global.base_namespace }}
spec:
  stripPrefix:
    prefixes:
    - /datamodel
    forceSlash: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datamodel-ingress
  namespace: {{ .Values.global.base_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: base-datamodel-strip-prefix@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /datamodel
        pathType: ImplementationSpecific
        backend:
          service:
            name: datamodel-service
            port:
              name: datamodel-http
---

