---
apiVersion: v1
kind: Secret
metadata:
  name: camic-registry
  namespace: {{ .Values.global.meta_namespace  }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"https://%s\": {\"auth\": \"%s\"}}}" .Values.global.registry_url (printf "%s:%s" .Values.global.credentials.registry_username .Values.global.credentials.registry_password | b64enc) | b64enc }}
---