http_proxy: ""
default_container_registry: "dktk-jip-registry.dkfz.de"
default_container_project: "kaapana" 
default_chart_registry: "https://dktk-jip-registry.dkfz.de/chartrepo/"
default_chart_project: "kaapana-public"
log_level: "WARN"
build_containers: true
push_containers: true
build_charts: true
push_charts: true
