http_proxy: ""
default_registry: "registry.hzdr.de/jonas.scherer/kaapana"
container_engine: "docker" # docker or podman
enable_build_kit: false
log_level: "INFO" # DEBUG, INFO, WARN or ERROR
build_only: false # Docker BuildKit: https://docs.docker.com/develop/develop-images/build_enhancements/
platform_filter: "" # comma sperated platform-chart-names
external_source_dirs: "" # comma sperated paths 
exit_on_error: true
enable_linting: false
