---
dependencies:
  - name: dcm4che-ldap
    version: "2.4.48-19.1"
    repository: file://deps/dcm4che-ldap
  - name: dcm4che-postgres
    version: "9.6.17-22"
    repository: file://deps/dcm4che-postgres
