---
dependencies:
  - name: dcm4che-ldap
    version: "2.4.56-23.1"
    repository: file://deps/dcm4che-ldap
  - name: dcm4che-postgres
    version: "9.6.20-23"
    repository: file://deps/dcm4che-postgres
