---
dependencies:
  - name: dcm4che-ldap
    version: "2.4.50-22.5-vdev"
    repository: file://deps/dcm4che-ldap
  - name: dcm4che-postgres
    version: "9.6.17-22.1-vdev"
    repository: file://deps/dcm4che-postgres
