---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: security-pages
  namespace: {{ .Values.global.security_namespace }}
  labels:
    k8s-app: security-pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: security-pages
  template:
    metadata:
      labels:
        app-name: security-pages
    spec:
      containers:
      - name: security-pages
        image: "{{ .Values.global.registry_url }}/security-pages:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy: {{ .Values.global.pull_policy_pods }}
        ports:
        - name: sec-pg-http
          containerPort: 5000
        env:
        - name: SECRET_KEY
          value: "kaapana-secret"
        - name: APPLICATION_ROOT
          value: "/security"
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: sec-pg-http
        #   initialDelaySeconds: 10
        #   periodSeconds: 20
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 500Mi
        # volumeMounts:
        #   - name: common-data-file
        #     mountPath: /app/jsons
      # volumes:
      # - name: common-data-file
      #   configMap:
      #     name: security-pages-config
      imagePullSecrets:
      - name: registry-secret
