---
apiVersion: v1
version: "2022.07.1-554"
appVersion: "2022.07.1-554"
name: rstudio-chart
description: Kaapana extension for RStudio-Server (Open Source Edition) (https://www.rstudio.com/products/rstudio/#rstudio-server)
keywords:
- kaapanaapplication
- kaapanaexperimental
