---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-helm-deployment
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: kube-helm
  template:
    metadata:
      labels:
        app-name: kube-helm
    spec:
      containers:
      - name: kube-helm
        image: {{ $.Values.global.registry_url }}/kube-helm:{{ $.Values.global.platform_abbr | default "uk" }}_{{ $.Values.global.platform_version | default "0" }}__0.1.3
        imagePullPolicy:  {{ $.Values.global.pull_policy_pods }}
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "100Mi"
        env: # Environment variables
        - name: SECRET_KEY
          value: kaapana-secret
        - name: APPLICATION_ROOT
          value: "/kube-helm-api"
        - name: HELM_PATH
          value: "/usr/local/bin/helm"
        - name: PLATFORM_ABBR
          value: {{ $.Values.global.platform_abbr }}
        - name: PLATFORM_VERSION
          value: {{ $.Values.global.platform_version }}
        - name: HELM_NAMESPACE
          value: {{ $.Values.global.helm_namespace }}
        - name: REGISTRY_URL
          value: {{ $.Values.global.registry_url }}
        - name: OFFLINE_MODE
          value: '{{ $.Values.global.offline_mode }}'
        - name: BASE_NAMESPACE
          value: {{ $.Values.global.base_namespace }}
        - name: FLOW_NAMESPACE
          value: {{ $.Values.global.flow_namespace }}
        - name: FLOW_JOBS_NAMESPACE
          value: {{ $.Values.global.flow_jobs_namespace }}
        - name: PULL_POLICY_PODS
          value: {{ $.Values.global.pull_policy_pods }}
        - name: PULL_POLICY_JOBS
          value: {{ $.Values.global.pull_policy_jobs }}
        - name: FAST_DATA_DIR
          value: {{ $.Values.global.fast_data_dir }}
        - name: SLOW_DATA_DIR
          value: {{ $.Values.global.slow_data_dir }}
{{- if $.Values.global.http_proxy }}
        - name: PROXY
          value: {{ $.Values.global.http_proxy }}
{{- end }}
        - name: MINIO_ACCESS_KEY
          value: "{{ $.Values.global.credentials_minio_username }}"
        - name: MINIO_SECRET_KEY
          value: "{{ $.Values.global.credentials_minio_password }}"
        - name: INSTANCE_NAME
          value: "{{ $.Values.global.instance_name }}"
        - name: HOSTNAME
          value: "{{ $.Values.global.hostname }}"
        - name: HTTPS_PORT
          value: "{{ $.Values.global.https_port }}"
        - name: KUBE_HELM_COLLECTIONS
          value: "{{- range $collection := $.Values.global.kube_helm_collections }}{{ $.Values.global.registry_url }}/{{ $collection.name }}:{{ $.Values.global.platform_abbr | default "uk" }}_{{ $.Values.global.platform_version | default "0" }}__{{ $collection.version }};{{- end }}"
        - name: PREINSTALL_EXTENSIONS
          value: '[{{- range $extension := $.Values.global.preinstall_extensions }}{"name": "{{ $extension.name }}", "version": "{{ $extension.version }}"},{{- end }}]'
        - name: PREFETCH_EXTENSIONS
          value: "{{ $.Values.global.prefetch_extensions }}"
        ports: # Port(s) on which your application runs
          - containerPort: 5000
        volumeMounts:
          - name: helmextensions
            mountPath: "/root/extensions"
      volumes:
      - name: helmextensions
        hostPath:
          path: {{ $.Values.global.fast_data_dir }}/extensions
          type: DirectoryOrCreate
      serviceAccountName: kubernetes-dashboard
      imagePullSecrets:
      - name: registry-secret
---