
---
apiVersion: batch/v1
kind: Job
metadata:
  name: extensions-init
  namespace: kube-system
spec:
  template:
    metadata:
      name: extensions-init
    spec:
      initContainers:
        - name: init
          image: {{ .Values.global.registry_url }}/service_checker:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__1.1
          imagePullPolicy: {{ .Values.global.pull_policy_jobs }}
          env:
            - name: WAIT
              value: "kube-helm,kube-helm-service.kube-system.svc,5000,/health-check"
            - name: DELAY
              value: "2"
            - name: TIMEOUT
              value: "10"
      containers:
      - name: extensions-init
        image: {{ .Values.global.registry_url }}/service_checker:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__1.1
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        command: ["/bin/sh", "-c"]
        args: ["echo -e \"import requests;requests.get('http://kube-helm-service.kube-system.svc:5000/extensions-init')\" | python3"]
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 2