
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-collections
  namespace: kube-system
spec:
  template:
    metadata:
      name: init-collections
    spec:
      containers:
      - name: init-collections
        image: {{ $.Values.global.registry_url }}/kube-helm:{{ $.Values.global.platform_abbr | default "uk" }}_{{ $.Values.global.platform_version | default "0" }}__0.1.3
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        command: ["python", "-u"]
        args: ["/app/init_collections.py"]
        env: # Environment variables copied from deployment.yaml
        - name: SECRET_KEY
          value: kaapana-secret
        - name: APPLICATION_ROOT
          value: "/kube-helm-api"
        - name: HELM_PATH
          value: "/usr/local/bin/helm"
        - name: PLATFORM_ABBR
          value: {{ $.Values.global.platform_abbr }}
        - name: PLATFORM_VERSION
          value: {{ $.Values.global.platform_version }}
        - name: HELM_NAMESPACE
          value: {{ $.Values.global.helm_namespace }}
        - name: REGISTRY_URL
          value: {{ $.Values.global.registry_url }}
        - name: OFFLINE_MODE
          value: '{{ $.Values.global.offline_mode }}'
        - name: BASE_NAMESPACE
          value: {{ $.Values.global.base_namespace }}
        - name: FLOW_NAMESPACE
          value: {{ $.Values.global.flow_namespace }}
        - name: FLOW_JOBS_NAMESPACE
          value: {{ $.Values.global.flow_jobs_namespace }}
        - name: PULL_POLICY_PODS
          value: {{ $.Values.global.pull_policy_pods }}
        - name: PULL_POLICY_JOBS
          value: {{ $.Values.global.pull_policy_jobs }}
        - name: FAST_DATA_DIR
          value: {{ $.Values.global.fast_data_dir }}
        - name: SLOW_DATA_DIR
          value: {{ $.Values.global.slow_data_dir }}
{{- if $.Values.global.http_proxy }}
        - name: PROXY
          value: {{ $.Values.global.http_proxy }}
{{- end }}
        - name: MINIO_ACCESS_KEY
          value: "{{ $.Values.global.credentials_minio_username }}"
        - name: MINIO_SECRET_KEY
          value: "{{ $.Values.global.credentials_minio_password }}"
        - name: INSTANCE_NAME
          value: "{{ $.Values.global.instance_name }}"
        - name: HOSTNAME
          value: "{{ $.Values.global.hostname }}"
        - name: HTTPS_PORT
          value: "{{ $.Values.global.https_port }}"
        - name: KUBE_HELM_COLLECTIONS
          value: "{{- range $collection := $.Values.global.kube_helm_collections }}{{ $.Values.global.registry_url }}/{{ $collection.name }}:{{ $.Values.global.platform_abbr | default "uk" }}_{{ $.Values.global.platform_version | default "0" }}__{{ $collection.version }};{{- end }}"
        - name: PREINSTALL_EXTENSIONS
          value: '[{{- range $extension := $.Values.global.preinstall_extensions }}{"name": "{{ $extension.name }}", "version": "{{ $extension.version }}"},{{- end }}]'
        - name: PREFETCH_EXTENSIONS
          value: "{{ $.Values.global.prefetch_extensions }}"
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 500Mi    
        volumeMounts:
          - name: helmextensions
            mountPath: "/root/extensions" 
      volumes:
      - name: helmextensions
        hostPath:
          path: {{ $.Values.global.fast_data_dir }}/extensions
          type: DirectoryOrCreate
      restartPolicy: Never
      serviceAccountName: kubernetes-dashboard
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-extensions
  namespace: kube-system
spec:
  template:
    metadata:
      name: init-extensions
    spec:
      initContainers:
        - name: wait-for-extensions
          image: {{ .Values.global.registry_url }}/service-checker:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__1.1
          imagePullPolicy: {{ .Values.global.pull_policy_jobs }}
          env:
            - name: FILES_AND_FOLDERS_EXISTS
              value: "{{- range $extension := $.Values.global.preinstall_extensions }}/root/extensions/{{ $extension.name }}-{{ $extension.version }}.tgz;{{- end }}"
            - name: DELAY
              value: "2"
            - name: TIMEOUT
              value: "10"
          volumeMounts:
            - name: helmextensions
              mountPath: "/root/extensions"
      containers:
      - name: preinstall-extensions
        image: {{ $.Values.global.registry_url }}/kube-helm:{{ $.Values.global.platform_abbr | default "uk" }}_{{ $.Values.global.platform_version | default "0" }}__0.1.3
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        command: ["python", "-u"]
        args: ["/app/preinstall_extensions.py"]
        env: # Environment variables copied from deployment.yaml
        - name: SECRET_KEY
          value: kaapana-secret
        - name: APPLICATION_ROOT
          value: "/kube-helm-api"
        - name: HELM_PATH
          value: "/usr/local/bin/helm"
        - name: PLATFORM_ABBR
          value: {{ $.Values.global.platform_abbr }}
        - name: PLATFORM_VERSION
          value: {{ $.Values.global.platform_version }}
        - name: HELM_NAMESPACE
          value: {{ $.Values.global.helm_namespace }}
        - name: REGISTRY_URL
          value: {{ $.Values.global.registry_url }}
        - name: OFFLINE_MODE
          value: '{{ $.Values.global.offline_mode }}'
        - name: BASE_NAMESPACE
          value: {{ $.Values.global.base_namespace }}
        - name: FLOW_NAMESPACE
          value: {{ $.Values.global.flow_namespace }}
        - name: FLOW_JOBS_NAMESPACE
          value: {{ $.Values.global.flow_jobs_namespace }}
        - name: PULL_POLICY_PODS
          value: {{ $.Values.global.pull_policy_pods }}
        - name: PULL_POLICY_JOBS
          value: {{ $.Values.global.pull_policy_jobs }}
        - name: FAST_DATA_DIR
          value: {{ $.Values.global.fast_data_dir }}
        - name: SLOW_DATA_DIR
          value: {{ $.Values.global.slow_data_dir }}
{{- if $.Values.global.http_proxy }}
        - name: PROXY
          value: {{ $.Values.global.http_proxy }}
{{- end }}
        - name: MINIO_ACCESS_KEY
          value: "{{ $.Values.global.credentials_minio_username }}"
        - name: MINIO_SECRET_KEY
          value: "{{ $.Values.global.credentials_minio_password }}"
        - name: INSTANCE_NAME
          value: "{{ $.Values.global.instance_name }}"
        - name: HOSTNAME
          value: "{{ $.Values.global.hostname }}"
        - name: HTTPS_PORT
          value: "{{ $.Values.global.https_port }}"
        - name: KUBE_HELM_COLLECTIONS
          value: "{{- range $collection := $.Values.global.kube_helm_collections }}{{ $.Values.global.registry_url }}/{{ $collection.name }}:{{ $.Values.global.platform_abbr | default "uk" }}_{{ $.Values.global.platform_version | default "0" }}__{{ $collection.version }};{{- end }}"
        - name: PREINSTALL_EXTENSIONS
          value: '[{{- range $extension := $.Values.global.preinstall_extensions }}{"name": "{{ $extension.name }}", "version": "{{ $extension.version }}"},{{- end }}]'
        - name: PREFETCH_EXTENSIONS
          value: "{{ $.Values.global.prefetch_extensions }}"
        volumeMounts:
          - name: helmextensions
            mountPath: "/root/extensions"
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 500Mi
{{- if $.Values.global.prefetch_extensions }}
      - name: prefetch-extensions
        image: {{ $.Values.global.registry_url }}/kube-helm:{{ $.Values.global.platform_abbr | default "uk" }}_{{ $.Values.global.platform_version | default "0" }}__0.1.3
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        command: ["python", "-u"]
        args: ["/app/prefetch_extensions.py"]
        env: # Environment variables copied from deployment.yaml
        - name: SECRET_KEY
          value: kaapana-secret
        - name: APPLICATION_ROOT
          value: "/kube-helm-api"
        - name: HELM_PATH
          value: "/usr/local/bin/helm"
        - name: PLATFORM_ABBR
          value: {{ $.Values.global.platform_abbr }}
        - name: PLATFORM_VERSION
          value: {{ $.Values.global.platform_version }}
        - name: HELM_NAMESPACE
          value: {{ $.Values.global.helm_namespace }}
        - name: REGISTRY_URL
          value: {{ $.Values.global.registry_url }}
        - name: OFFLINE_MODE
          value: '{{ $.Values.global.offline_mode }}'
        - name: BASE_NAMESPACE
          value: {{ $.Values.global.base_namespace }}
        - name: FLOW_NAMESPACE
          value: {{ $.Values.global.flow_namespace }}
        - name: FLOW_JOBS_NAMESPACE
          value: {{ $.Values.global.flow_jobs_namespace }}
        - name: PULL_POLICY_PODS
          value: {{ $.Values.global.pull_policy_pods }}
        - name: PULL_POLICY_JOBS
          value: {{ $.Values.global.pull_policy_jobs }}
        - name: FAST_DATA_DIR
          value: {{ $.Values.global.fast_data_dir }}
        - name: SLOW_DATA_DIR
          value: {{ $.Values.global.slow_data_dir }}
{{- if $.Values.global.http_proxy }}
        - name: PROXY
          value: {{ $.Values.global.http_proxy }}
{{- end }}
        - name: MINIO_ACCESS_KEY
          value: "{{ $.Values.global.credentials_minio_username }}"
        - name: MINIO_SECRET_KEY
          value: "{{ $.Values.global.credentials_minio_password }}"
        - name: INSTANCE_NAME
          value: "{{ $.Values.global.instance_name }}"
        - name: HOSTNAME
          value: "{{ $.Values.global.hostname }}"
        - name: HTTPS_PORT
          value: "{{ $.Values.global.https_port }}"
        - name: KUBE_HELM_COLLECTIONS
          value: "{{- range $collection := $.Values.global.kube_helm_collections }}{{ $.Values.global.registry_url }}/{{ $collection.name }}:{{ $.Values.global.platform_abbr | default "uk" }}_{{ $.Values.global.platform_version | default "0" }}__{{ $collection.version }};{{- end }}"
        - name: PREINSTALL_EXTENSIONS
          value: '[{{- range $extension := $.Values.global.preinstall_extensions }}{"name": "{{ $extension.name }}", "version": "{{ $extension.version }}"},{{- end }}]'
        - name: PREFETCH_EXTENSIONS
          value: "{{ $.Values.global.prefetch_extensions }}"
        volumeMounts:
          - name: helmextensions
            mountPath: "/root/extensions"
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 500Mi
{{- end }}
      restartPolicy: Never
      volumes:
      - name: helmextensions
        hostPath:
          path: {{ $.Values.global.fast_data_dir }}/extensions
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 2