---
# data-jobs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: af-data-pv-volume-jobs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "10Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}/workflows/data"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.jobs_namespace }}"
    name: af-data-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: af-data-pv-claim
  namespace: "{{ .Values.global.jobs_namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Mi"
  volumeName: "af-data-pv-volume-jobs"
---
# minio-jobs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume-jobs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "10Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}/minio"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.jobs_namespace }}"
    name: minio-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  namespace: "{{ .Values.global.jobs_namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Mi"
  volumeName: "minio-pv-volume-jobs"
---
# tensorboard-jobs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tb-pv-volume-jobs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "10Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}/tensorboard"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.jobs_namespace }}"
    name: tb-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tb-pv-claim
  namespace: "{{ .Values.global.jobs_namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Mi"
  volumeName: "tb-pv-volume-jobs"
---
# models-jobs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-pv-volume-jobs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "10Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}/workflows/models"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.jobs_namespace }}"
    name: models-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pv-claim
  namespace: "{{ .Values.global.jobs_namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Mi"
  volumeName: "models-pv-volume-jobs"
---