kind: Deployment
apiVersion: apps/v1
metadata:
  name: tensorboard{{- if .Values.multi_instance_suffix }}-{{ .Values.multi_instance_suffix }}{{- end }}
  namespace: {{ .Values.global.base_namespace }}
  labels:
    k8s-app: tensorboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: tensorboard{{- if .Values.multi_instance_suffix }}-{{ .Values.multi_instance_suffix }}{{- end }}
  template:
    metadata:
      labels:
        app-name: tensorboard{{- if .Values.multi_instance_suffix }}-{{ .Values.multi_instance_suffix }}{{- end }}
    spec:
      containers:
      - name: tensorboard
        image: {{  .Values.global.registry_url }}{{  .Values.global.registry_project }}/tensorboard:1.0-vdev
        imagePullPolicy:  Always
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "1Gi"
        env:
          - name: INGRESS_PATH
            value: {{ .Values.ingress_path }}
        volumeMounts:
          - name: tensorboard-files
            mountPath: /data
      volumes:
      - name: tensorboard-files
        hostPath:
          {{- if .Values.mount_path }}
          path: {{ .Values.mount_path }}
          {{- else }}
          path: {{ .Values.global.fast_data_dir }}/workflows/data
          {{- end }}
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: camic-registry