apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-errors
  namespace: kube-system
spec:
  errors:
    status:
      - 400-500
    query: /{status}
    service:
      name: error-pages-service
      namespace: kube-system
      port: 5000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-auth
  namespace: kube-system
spec:
  forwardAuth:
    address: https://{{ required "A valid hostname (or fqdn) is required!" $.Values.global.hostname }}:{{ .Values.global.https_port }}/oauth2/auth
    trustForwardHeader: true
    status:
      - 400-500
    query: /{status}
    service:
      name: error-pages-service
      namespace: kube-system
      port: 5000