---
global:
    registry_url: ""
    registry_project: ""
    pull_policy_pods: "IfNotPresent"
    flow_namespace: "flow"
    flow_jobs_namespace: "flow-jobs"
    hostname: 
    credentials:
        minio_username: "jipadmin"
        minio_password: "DKjipTK2019"

    fast_data_dir: /home/kaapana
    slow_data_dir: /home/kaapana

    